# Generated by Django 5.1.1 on 2024-09-12 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                ("categoryID", models.AutoField(primary_key=True, serialize=False)),
                ("categoryName", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("productID", models.AutoField(primary_key=True, serialize=False)),
                ("productName", models.CharField(max_length=200)),
                ("productImage", models.FileField(upload_to="products/")),
                ("stockQuantity", models.IntegerField()),
                ("productPrice", models.FloatField()),
                (
                    "categoryName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category",
                        to="mainapp.productcategory",
                    ),
                ),
            ],
        ),
    ]
